// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/url"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создание форума
	// (POST /forum/create)
	ForumCreate(c *fiber.Ctx) error
	// Создание ветки
	// (POST /forum/{slug}/create)
	ThreadCreate(c *fiber.Ctx, slug string) error
	// Получение информации о форуме
	// (GET /forum/{slug}/details)
	ForumGetOne(c *fiber.Ctx, slug string) error
	// Список ветвей обсужления форума
	// (GET /forum/{slug}/threads)
	ForumGetThreads(c *fiber.Ctx, slug string, params ForumGetThreadsParams) error
	// Пользователи данного форума
	// (GET /forum/{slug}/users)
	ForumGetUsers(c *fiber.Ctx, slug string, params ForumGetUsersParams) error
	// Получение информации о ветке обсуждения
	// (GET /post/{id}/details)
	PostGetOne(c *fiber.Ctx, id int64, params PostGetOneParams) error
	// Изменение сообщения
	// (POST /post/{id}/details)
	PostUpdate(c *fiber.Ctx, id int64) error
	// Очистка всех данных в базе
	// (POST /service/clear)
	Clear(c *fiber.Ctx) error
	// Получение инфомарции о базе данных
	// (GET /service/status)
	Status(c *fiber.Ctx) error
	// Создание новых постов
	// (POST /thread/{slug_or_id}/create)
	PostsCreate(c *fiber.Ctx, slugOrId string) error
	// Получение информации о ветке обсуждения
	// (GET /thread/{slug_or_id}/details)
	ThreadGetOne(c *fiber.Ctx, slugOrId string) error
	// Обновление ветки
	// (POST /thread/{slug_or_id}/details)
	ThreadUpdate(c *fiber.Ctx, slugOrId string) error
	// Сообщения данной ветви обсуждения
	// (GET /thread/{slug_or_id}/posts)
	ThreadGetPosts(c *fiber.Ctx, slugOrId string, params ThreadGetPostsParams) error
	// Проголосовать за ветвь обсуждения
	// (POST /thread/{slug_or_id}/vote)
	ThreadVote(c *fiber.Ctx, slugOrId string) error
	// Создание нового пользователя
	// (POST /user/{nickname}/create)
	UserCreate(c *fiber.Ctx, nickname string) error
	// Получение информации о пользователе
	// (GET /user/{nickname}/profile)
	UserGetOne(c *fiber.Ctx, nickname string) error
	// Изменение данных о пользователе
	// (POST /user/{nickname}/profile)
	UserUpdate(c *fiber.Ctx, nickname string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ForumCreate operation middleware
func (siw *ServerInterfaceWrapper) ForumCreate(c *fiber.Ctx) error {

	return siw.Handler.ForumCreate(c)
}

// ThreadCreate operation middleware
func (siw *ServerInterfaceWrapper) ThreadCreate(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Params("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug: %w", err).Error())
	}

	return siw.Handler.ThreadCreate(c, slug)
}

// ForumGetOne operation middleware
func (siw *ServerInterfaceWrapper) ForumGetOne(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Params("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug: %w", err).Error())
	}

	return siw.Handler.ForumGetOne(c, slug)
}

// ForumGetThreads operation middleware
func (siw *ServerInterfaceWrapper) ForumGetThreads(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Params("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ForumGetThreadsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", query, &params.Since)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter since: %w", err).Error())
	}

	// ------------- Optional query parameter "desc" -------------

	err = runtime.BindQueryParameter("form", true, false, "desc", query, &params.Desc)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter desc: %w", err).Error())
	}

	return siw.Handler.ForumGetThreads(c, slug, params)
}

// ForumGetUsers operation middleware
func (siw *ServerInterfaceWrapper) ForumGetUsers(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Params("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ForumGetUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", query, &params.Since)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter since: %w", err).Error())
	}

	// ------------- Optional query parameter "desc" -------------

	err = runtime.BindQueryParameter("form", true, false, "desc", query, &params.Desc)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter desc: %w", err).Error())
	}

	return siw.Handler.ForumGetUsers(c, slug, params)
}

// PostGetOne operation middleware
func (siw *ServerInterfaceWrapper) PostGetOne(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostGetOneParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "related" -------------

	err = runtime.BindQueryParameter("form", false, false, "related", query, &params.Related)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter related: %w", err).Error())
	}

	return siw.Handler.PostGetOne(c, id, params)
}

// PostUpdate operation middleware
func (siw *ServerInterfaceWrapper) PostUpdate(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.PostUpdate(c, id)
}

// Clear operation middleware
func (siw *ServerInterfaceWrapper) Clear(c *fiber.Ctx) error {

	return siw.Handler.Clear(c)
}

// Status operation middleware
func (siw *ServerInterfaceWrapper) Status(c *fiber.Ctx) error {

	return siw.Handler.Status(c)
}

// PostsCreate operation middleware
func (siw *ServerInterfaceWrapper) PostsCreate(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug_or_id" -------------
	var slugOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "slug_or_id", c.Params("slug_or_id"), &slugOrId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug_or_id: %w", err).Error())
	}

	return siw.Handler.PostsCreate(c, slugOrId)
}

// ThreadGetOne operation middleware
func (siw *ServerInterfaceWrapper) ThreadGetOne(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug_or_id" -------------
	var slugOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "slug_or_id", c.Params("slug_or_id"), &slugOrId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug_or_id: %w", err).Error())
	}

	return siw.Handler.ThreadGetOne(c, slugOrId)
}

// ThreadUpdate operation middleware
func (siw *ServerInterfaceWrapper) ThreadUpdate(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug_or_id" -------------
	var slugOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "slug_or_id", c.Params("slug_or_id"), &slugOrId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug_or_id: %w", err).Error())
	}

	return siw.Handler.ThreadUpdate(c, slugOrId)
}

// ThreadGetPosts operation middleware
func (siw *ServerInterfaceWrapper) ThreadGetPosts(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug_or_id" -------------
	var slugOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "slug_or_id", c.Params("slug_or_id"), &slugOrId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug_or_id: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ThreadGetPostsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", query, &params.Since)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter since: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	// ------------- Optional query parameter "desc" -------------

	err = runtime.BindQueryParameter("form", true, false, "desc", query, &params.Desc)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter desc: %w", err).Error())
	}

	return siw.Handler.ThreadGetPosts(c, slugOrId, params)
}

// ThreadVote operation middleware
func (siw *ServerInterfaceWrapper) ThreadVote(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "slug_or_id" -------------
	var slugOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "slug_or_id", c.Params("slug_or_id"), &slugOrId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter slug_or_id: %w", err).Error())
	}

	return siw.Handler.ThreadVote(c, slugOrId)
}

// UserCreate operation middleware
func (siw *ServerInterfaceWrapper) UserCreate(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "nickname" -------------
	var nickname string

	err = runtime.BindStyledParameterWithOptions("simple", "nickname", c.Params("nickname"), &nickname, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter nickname: %w", err).Error())
	}

	return siw.Handler.UserCreate(c, nickname)
}

// UserGetOne operation middleware
func (siw *ServerInterfaceWrapper) UserGetOne(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "nickname" -------------
	var nickname string

	err = runtime.BindStyledParameterWithOptions("simple", "nickname", c.Params("nickname"), &nickname, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter nickname: %w", err).Error())
	}

	return siw.Handler.UserGetOne(c, nickname)
}

// UserUpdate operation middleware
func (siw *ServerInterfaceWrapper) UserUpdate(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "nickname" -------------
	var nickname string

	err = runtime.BindStyledParameterWithOptions("simple", "nickname", c.Params("nickname"), &nickname, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter nickname: %w", err).Error())
	}

	return siw.Handler.UserUpdate(c, nickname)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/forum/create", wrapper.ForumCreate)

	router.Post(options.BaseURL+"/forum/:slug/create", wrapper.ThreadCreate)

	router.Get(options.BaseURL+"/forum/:slug/details", wrapper.ForumGetOne)

	router.Get(options.BaseURL+"/forum/:slug/threads", wrapper.ForumGetThreads)

	router.Get(options.BaseURL+"/forum/:slug/users", wrapper.ForumGetUsers)

	router.Get(options.BaseURL+"/post/:id/details", wrapper.PostGetOne)

	router.Post(options.BaseURL+"/post/:id/details", wrapper.PostUpdate)

	router.Post(options.BaseURL+"/service/clear", wrapper.Clear)

	router.Get(options.BaseURL+"/service/status", wrapper.Status)

	router.Post(options.BaseURL+"/thread/:slug_or_id/create", wrapper.PostsCreate)

	router.Get(options.BaseURL+"/thread/:slug_or_id/details", wrapper.ThreadGetOne)

	router.Post(options.BaseURL+"/thread/:slug_or_id/details", wrapper.ThreadUpdate)

	router.Get(options.BaseURL+"/thread/:slug_or_id/posts", wrapper.ThreadGetPosts)

	router.Post(options.BaseURL+"/thread/:slug_or_id/vote", wrapper.ThreadVote)

	router.Post(options.BaseURL+"/user/:nickname/create", wrapper.UserCreate)

	router.Get(options.BaseURL+"/user/:nickname/profile", wrapper.UserGetOne)

	router.Post(options.BaseURL+"/user/:nickname/profile", wrapper.UserUpdate)

}
