// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: additional.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkForumExists = `-- name: CheckForumExists :one
SELECT slug FROM forums WHERE slug = $1
`

func (q *Queries) CheckForumExists(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, checkForumExists, slug)
	err := row.Scan(&slug)
	return slug, err
}

const checkThreadExistsById = `-- name: CheckThreadExistsById :one

SELECT id FROM threads WHERE id = $1
`

// Existence check queries
func (q *Queries) CheckThreadExistsById(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, checkThreadExistsById, id)
	err := row.Scan(&id)
	return id, err
}

const checkThreadExistsBySlug = `-- name: CheckThreadExistsBySlug :one
SELECT slug FROM threads WHERE slug = $1
`

func (q *Queries) CheckThreadExistsBySlug(ctx context.Context, slug pgtype.Text) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, checkThreadExistsBySlug, slug)
	err := row.Scan(&slug)
	return slug, err
}

const createThread = `-- name: CreateThread :one

INSERT INTO threads (slug, created, title, message, user_nn, forum_slug)
VALUES ($1, $2, $3, $4, $5, (SELECT f.slug FROM forums f WHERE f.slug = $6))
RETURNING id, forum_slug, slug
`

type CreateThreadParams struct {
	Slug    pgtype.Text
	Created pgtype.Timestamptz
	Title   string
	Message pgtype.Text
	UserNn  string
	Slug_2  string
}

type CreateThreadRow struct {
	ID        int32
	ForumSlug string
	Slug      pgtype.Text
}

// Thread queries
func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (CreateThreadRow, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.Slug,
		arg.Created,
		arg.Title,
		arg.Message,
		arg.UserNn,
		arg.Slug_2,
	)
	var i CreateThreadRow
	err := row.Scan(&i.ID, &i.ForumSlug, &i.Slug)
	return i, err
}

const getForumBySlugLight = `-- name: GetForumBySlugLight :one

SELECT slug, title, user_nn 
FROM forums 
WHERE slug = $1
`

type GetForumBySlugLightRow struct {
	Slug   string
	Title  string
	UserNn string
}

// Forum queries
func (q *Queries) GetForumBySlugLight(ctx context.Context, slug string) (GetForumBySlugLightRow, error) {
	row := q.db.QueryRow(ctx, getForumBySlugLight, slug)
	var i GetForumBySlugLightRow
	err := row.Scan(&i.Slug, &i.Title, &i.UserNn)
	return i, err
}

const updatePostMessage = `-- name: UpdatePostMessage :exec

UPDATE posts 
SET message = $1, isedited = TRUE
WHERE id = $2
`

type UpdatePostMessageParams struct {
	Message string
	ID      int64
}

// Post queries
func (q *Queries) UpdatePostMessage(ctx context.Context, arg UpdatePostMessageParams) error {
	_, err := q.db.Exec(ctx, updatePostMessage, arg.Message, arg.ID)
	return err
}

const updateThreadById = `-- name: UpdateThreadById :exec
UPDATE threads 
SET title = COALESCE($2, title), 
    message = COALESCE($3, message)
WHERE id = $1
`

type UpdateThreadByIdParams struct {
	ID      int32
	Title   pgtype.Text
	Message pgtype.Text
}

func (q *Queries) UpdateThreadById(ctx context.Context, arg UpdateThreadByIdParams) error {
	_, err := q.db.Exec(ctx, updateThreadById, arg.ID, arg.Title, arg.Message)
	return err
}

const updateThreadBySlug = `-- name: UpdateThreadBySlug :exec
UPDATE threads 
SET title = COALESCE($2, title), 
    message = COALESCE($3, message)
WHERE slug = $1
`

type UpdateThreadBySlugParams struct {
	Slug    pgtype.Text
	Title   pgtype.Text
	Message pgtype.Text
}

func (q *Queries) UpdateThreadBySlug(ctx context.Context, arg UpdateThreadBySlugParams) error {
	_, err := q.db.Exec(ctx, updateThreadBySlug, arg.Slug, arg.Title, arg.Message)
	return err
}

const upsertVoteById = `-- name: UpsertVoteById :exec

INSERT INTO votes (thread_id, user_nn, voice) 
VALUES ($1, $2, $3) 
ON CONFLICT ON CONSTRAINT votes_thread_user_unique 
DO UPDATE SET voice = EXCLUDED.voice
`

type UpsertVoteByIdParams struct {
	ThreadID int32
	UserNn   string
	Voice    pgtype.Int4
}

// Vote queries
func (q *Queries) UpsertVoteById(ctx context.Context, arg UpsertVoteByIdParams) error {
	_, err := q.db.Exec(ctx, upsertVoteById, arg.ThreadID, arg.UserNn, arg.Voice)
	return err
}

const upsertVoteBySlug = `-- name: UpsertVoteBySlug :exec
INSERT INTO votes (thread_id, user_nn, voice) 
VALUES ((SELECT id FROM threads WHERE slug = $1), $2, $3) 
ON CONFLICT ON CONSTRAINT votes_thread_user_unique 
DO UPDATE SET voice = EXCLUDED.voice
`

type UpsertVoteBySlugParams struct {
	Slug   pgtype.Text
	UserNn string
	Voice  pgtype.Int4
}

func (q *Queries) UpsertVoteBySlug(ctx context.Context, arg UpsertVoteBySlugParams) error {
	_, err := q.db.Exec(ctx, upsertVoteBySlug, arg.Slug, arg.UserNn, arg.Voice)
	return err
}
