// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Forum struct {
	Slug    string
	Title   string
	UserNn  string
	Posts   pgtype.Int4
	Threads pgtype.Int4
}

type ForumUser struct {
	ForumSlug string
	UserID    string
}

type Post struct {
	ID       int32
	Created  pgtype.Timestamptz
	Isedited pgtype.Bool
	Message  string
	ParentID pgtype.Int4
	UserNn   string
	ThreadID int32
	Path     []int32
}

type Thread struct {
	ID        int32
	Slug      pgtype.Text
	Created   pgtype.Timestamptz
	Title     string
	Message   pgtype.Text
	Votes     pgtype.Int4
	UserNn    string
	ForumSlug string
}

type User struct {
	ID       int32
	Nickname string
	Fullname string
	Email    string
	About    pgtype.Text
}

type Vote struct {
	ThreadID int32
	UserNn   string
	Voice    pgtype.Int4
}
