// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post.sql

package db

import (
	"context"
)

const listByID = `-- name: ListByID :many
SELECT id, created, isedited, message, parent_id, user_nn, thread_id, path
FROM posts
WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListByID(ctx context.Context, dollar_1 []int64) ([]Post, error) {
	rows, err := q.db.Query(ctx, listByID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Isedited,
			&i.Message,
			&i.ParentID,
			&i.UserNn,
			&i.ThreadID,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostMessage = `-- name: UpdatePostMessage :exec
UPDATE posts 
SET message = $1, isedited = TRUE
WHERE id = $2
`

type UpdatePostMessageParams struct {
	Message string
	ID      int64
}

func (q *Queries) UpdatePostMessage(ctx context.Context, arg UpdatePostMessageParams) error {
	_, err := q.db.Exec(ctx, updatePostMessage, arg.Message, arg.ID)
	return err
}
