// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vote.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertVoteById = `-- name: UpsertVoteById :exec
INSERT INTO votes (thread_id, user_nn, voice) 
VALUES ($1, $2, $3) 
ON CONFLICT ON CONSTRAINT votes_thread_user_unique 
DO UPDATE SET voice = EXCLUDED.voice
`

type UpsertVoteByIdParams struct {
	ThreadID int32
	UserNn   string
	Voice    pgtype.Int4
}

func (q *Queries) UpsertVoteById(ctx context.Context, arg UpsertVoteByIdParams) error {
	_, err := q.db.Exec(ctx, upsertVoteById, arg.ThreadID, arg.UserNn, arg.Voice)
	return err
}

const upsertVoteBySlug = `-- name: UpsertVoteBySlug :exec
INSERT INTO votes (thread_id, user_nn, voice) 
VALUES ((SELECT id FROM threads WHERE slug = $1), $2, $3) 
ON CONFLICT ON CONSTRAINT votes_thread_user_unique 
DO UPDATE SET voice = EXCLUDED.voice
`

type UpsertVoteBySlugParams struct {
	Slug   pgtype.Text
	UserNn string
	Voice  pgtype.Int4
}

func (q *Queries) UpsertVoteBySlug(ctx context.Context, arg UpsertVoteBySlugParams) error {
	_, err := q.db.Exec(ctx, upsertVoteBySlug, arg.Slug, arg.UserNn, arg.Voice)
	return err
}
